apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/toanbui1991/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Sat, 22 Jul 2023 08:02:25 +07
        provider: minikube.sigs.k8s.io
        version: v1.30.1
      name: cluster_info
    server: https://192.168.59.134:8443
  name: istio
- cluster:
    certificate-authority: /home/toanbui1991/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Sat, 22 Jul 2023 07:49:19 +07
        provider: minikube.sigs.k8s.io
        version: v1.30.1
      name: cluster_info
    server: https://192.168.59.133:8443
  name: minikube
contexts:
- context:
    cluster: istio
    extensions:
    - extension:
        last-update: Sat, 22 Jul 2023 08:02:25 +07
        provider: minikube.sigs.k8s.io
        version: v1.30.1
      name: context_info
    namespace: default
    user: istio
  name: istio
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Sat, 22 Jul 2023 07:49:19 +07
        provider: minikube.sigs.k8s.io
        version: v1.30.1
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: istio
  user:
    client-certificate: /home/toanbui1991/.minikube/profiles/istio/client.crt
    client-key: /home/toanbui1991/.minikube/profiles/istio/client.key
- name: minikube
  user:
    client-certificate: /home/toanbui1991/.minikube/profiles/minikube/client.crt
    client-key: /home/toanbui1991/.minikube/profiles/minikube/client.key
